# Generated by Django 2.2.4 on 2019-09-17 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biller',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='biller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.Biller'),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.Customer'),
        ),
    ]
