# Generated by Django 2.2.4 on 2019-09-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='account',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
