# Generated by Django 2.2.4 on 2019-09-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20190917_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='account',
            field=models.IntegerField(null=True),
        ),
    ]
