# Generated by Django 2.2.4 on 2019-09-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20190917_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
