# Generated by Django 2.2.4 on 2019-10-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20190923_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='date published'),
        ),
    ]
