# Generated by Django 2.2.4 on 2019-11-03 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_duser_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='duser',
            managers=[
            ],
        ),
    ]
